//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Review struct {
	ID        int64 `sql:"primary_key"`
	Rating    *int32
	Content   *string
	UserID    int64
	TenantID  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}
